name: Create Release

on:
  workflow_dispatch:

jobs:
  build-win-gdigrab:
    uses: ./.github/workflows/build-windows.yml
    with:
      capture_device: 'gdigrab'

  build-linux:
    uses: ./.github/workflows/build-linux.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml

  publish-release:
    needs: [build-win-gdigrab, build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ needs.build-linux.outputs.ffmpeg_version }}.${{ github.run_number }}
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List Artifacts
        run: ls -R artifacts

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --title "FFmpeg Minimal ${{ env.VERSION }}" \
            --notes "Build of FFmpeg ${{ needs.build-linux.outputs.ffmpeg_version }} with libvpx support." \
            artifacts/*
